name: Build and deploy Node.js app to Azure Web App - quran-tafsir

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend  # CHANGED: Only upload the backend directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C739C9B3847D413A8536434483FC41D0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_116E44255B4A4BDA9CDA253BB2C3AB8E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5EF210AAD4694EF09B5E33D3C3628CD2 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quran-tafsir'
          slot-name: 'Production'
          package: .  # CHANGED: Now correct because artifact only contains backend
          runtime-stack: 'NODE|20-lts'
          startup-command: 'npm start'
